// <auto-generated />
namespace JogosDeGuerraModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EstadoBatalha20181106Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EstadoBatalha20181106Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201811061251062_EstadoBatalha-20181106-Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
