// <auto-generated />
namespace JogosDeGuerraWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EstadoBatalha20181106 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EstadoBatalha20181106));
        
        string IMigrationMetadata.Id
        {
            get { return "201811061247525_EstadoBatalha-20181106"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
